### ISSUE TITLE
Location for new wake word?

### ISSUE THREAD

**Issue by jmorris644** [rhasspy/wyoming-openwakeword#11]
I have created a new wake word and cannot figure out where to put it. I tried putting the files in the Custom dir. It did not work. Here is my docker-compose that I use to run it.

```
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - /home/joe/whisper/custom/models:/custom
    restart: unless-stopped
    ports:
      - 10400:10400
      ```
